version: 2.1
jobs:
  deploy:
    working_directory: ~/project
    docker: 
      - image: circleci/node:10
    steps: 
      - checkout
      - run: ls
      - run: cd habit-tracker
      - run: ls
      #Download and cache dependencies
      - restore_cache:
            keys:
              - v1-dependencies-{{ checksum "package.json" }}
              # fallback to using the latest cache if no exact match is found
              - v1-dependencies-
      - run: npm install
      - save_cache: 
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm build 
      - run: npm netlify:deploy
workflows:
  test_app:
    jobs:
      - deploy 