version: 2.1
jobs:
  deploy:
    working_directory: ~/project
    docker: 
      - image: circleci/node:10
  steps: 
    - checkout
    - Download and cache dependencies
    - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
    - run: npm install
    - save_cache: 
        paths:
          - node_modules
        key: v1-dependencies-{{ checksum "package.json" }}
    - run: npm build 
    - run: npm netlify:deploy
  test:
    working_directory: ~/project
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          working_directory: ~/project/habit-tracker
          name: Install Dependencies
          command: npm ci
      - run:
          working_directory: ~/project/habit-tracker
          name: Run Tests
          environment:
            JEST_JUNIT_OUTPUT_DIR: ./reports/junit/
          command: npm run test
workflows:
  test_app:
    jobs:
      - deploy 